#!/bin/bash
#
# Script to monitor Raspberry Pi
#

# Author: Etienne le Roux (etienne@linux.com) for ONMS.Net
# Address: PoBox 634, Menlyn Retail Park, Pretoria, South Africa, 0063

#
#    Copyright (C) 2012 Etienne le Roux
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

export PATH=$PATH:/opt/vc/bin
export LD_LIBRARY_PATH=$LD_LIBRARYPATH:/opt/vc/lib

temp=`/opt/vc/bin/vcgencmd measure_temp | sed s/^.....//`
echo "Current Temperature is $temp"

mhz=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq | sed s/...$//`
echo "CPU Frequency in MHz is $mhz"

